catalog:
  "@eslint/js": ^9
  "@rsbuild/core": ^1
  "@rsbuild/plugin-react": ^1
  "@rsbuild/plugin-source-build": ^1
  "@rslib/core": ^0.19
  "@rstest/adapter-rsbuild": ^0.2
  "@rstest/adapter-rslib": ^0.2
  "@rstest/core": ^0.8
  "@testing-library/dom": ^10
  "@testing-library/jest-dom": ^6
  "@testing-library/react": ^16
  "@types/react": ^19
  "@types/react-dom": ^19
  eslint: ^9
  eslint-plugin-react-hooks: ^7
  eslint-plugin-react-refresh: ^0.5
  globals: ^17
  happy-dom: ^20
  prettier: ^3
  react: ^19
  react-dom: ^19
  typescript: ^5
  typescript-eslint: ^8

enableTelemetry: false

nodeLinker: pnpm

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
  os:
    - current
    - darwin
    - linux
