catalog:
  "@eslint/js": ^9
  eslint: ^9
  eslint-plugin-react-hooks: ^7
  eslint-plugin-react-refresh: ^0.5
  globals: ^17
  prettier: ^3.8.1
  typescript: ^5
  typescript-eslint: ^8

enableGlobalCache: false

enableTelemetry: false

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
  os:
    - current
    - darwin
    - linux
